# Generated by Django 3.1.7 on 2021-06-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210625_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='instagram_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
