# Generated by Django 3.1.7 on 2021-03-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userproject', '0004_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.AddField(
            model_name='project',
            name='company_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
